source 'https://rubygems.org'

gem 'guard', '~> 2.13.0'
gem 'guard-minitest', '~> 2.4.4'
gem 'kramdown', '~> 1.8.0'
gem 'middleman-core', '~> 3.4.0'
gem 'middleman-livereload', '~> 3.4.3'
gem 'middleman-s3_sync', '~> 3.0.47'
gem 'middleman-syntax', '~> 2.0.0'
gem 'rake', '~> 10.4.2'
