source "https://rubygems.org"

gem "guard", "~> 2.14.0"
gem "guard-minitest", "~> 2.4.4"
gem "kramdown", "~> 1.13.0"
gem "middleman-core", "~> 4.2.0"
gem "middleman-livereload", "~> 3.4.3"
gem "middleman-s3_sync", "~> 4.0.0"
gem "middleman-syntax", "~> 3.0.0"
gem "rake"
gem "mime-types"
