source "https://rubygems.org"

gem "guard", "~> 2.16.1"
gem "guard-minitest", "~> 2.4.4"
gem "kramdown", "~> 2.1.0"
gem "middleman-core", "~> 4.3.5"
gem "middleman-livereload", "~> 3.4.3"
gem "middleman-s3_sync", "~> 4.0.0"
gem "middleman-syntax", "~> 3.2.0"
gem "rake"
gem "mime-types"
